#
#Thu Mar 12 13:56:00 COT 2026
goog\:chromeOptions={args\=[--incognito, --disable-save-password-bubble, --remote-allow-origins\=*, --disable-notifications], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
